tcp:
  server:
    port: 65535
    max-connection: 100
    charset: utf-8
  client:
    host: localhost
    port: 65535
    connection-timeout: 1000 # millis
    read-timeout: 5000 # millis
    charset: utf-8
    pool:
      min-idle: 10
      max-idle: 10
      max-total: 100
