@startuml

skinparam ClassAttributeIconSize 0

package server {
  abstract class AbstractTcpServer {
    # int port
    + {abstract} void handleMessage(InputStream reader, OutputStream writer)
    + void start()
    + void stop()
  }

  package example {
    class EchoServer extends AbstractTcpServer {
        + void handleMessage(InputStream reader, OutputStream writer)
     }
  }
}

package java.net {
  class ServerSocket
  class Socket
}

AbstractTcpServer ..> ServerSocket
AbstractTcpServer ..> Socket

@enduml
