@startuml

skinparam ClassAttributeIconSize 0

package tcp {
  package message {
    package strategy {
      interface HeaderStrategy {
        + byte[] read(InputStream reader)
        + void write(OutputStream writer, byte[] body)
      }

      class LengthAwareHeaderStrategy implements HeaderStrategy {
        - String lpadChar
        - int headerLength
        - Charset charset
      }

      class NullHeaderStrategy implements HeaderStrategy
    }
  }

  package server {
    interface TcpServer {
      + void start()
      + void stop()
      + void receive(InputStream, OutputStream)
    }

    abstract class AbstractTcpServer implements TcpServer {
      # int port
    }

    package example {
      class EchoServer extends AbstractTcpServer {}
    }
  }
}

package java.net {
  class ServerSocket
  class Socket
}

AbstractTcpServer .left.> ServerSocket
AbstractTcpServer .left.> Socket
AbstractTcpServer --> HeaderStrategy

@enduml
