@startuml

skinparam ClassAttributeIconSize 0

package server {
  interface TcpServer {
    + start(): void
    + stop(): void
    + receive(InputStream, OutputStream): void
  }

  abstract class AbstractTcpServer implements TcpServer {
    # int port
  }

  package example {
    class EchoServer extends AbstractTcpServer {}
  }
}

package java.net {
  class ServerSocket
  class Socket
}

AbstractTcpServer ..> ServerSocket
AbstractTcpServer ..> Socket

@enduml
